/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": 'eu-west-1',
    "aws_cognito_region": 'eu-west-1',
    "aws_cognito_identity_pool_id": 'eu-west-1:7b5da013-2301-4c5b-84b9-11fff633021f',
    "aws_user_pools_id": 'eu-west-1_T1s4x2kQ3',
    "aws_user_pools_web_client_id": '291uiqh3phrf469np4f7sfgi8q',
}; 

export default awsmobile;
