/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": 'eu-west-1',
    "aws_cognito_region": 'eu-west-1',
    "aws_cognito_identity_pool_id": 'eu-west-1:e5f8307a-3446-420c-a475-a43877f2697f',
    "aws_user_pools_id": 'eu-west-1_TtSfIVQmL',
    "aws_user_pools_web_client_id": '7d2dtubid3eop3s876u4klq7a6',
}; 
